### ISSUE TITLE
WooCommerce HPOS release testing

### ISSUE THREAD

**Issue by andershelt** [smartsendio/woocommerce#44]
Knapperne til oprettelse af labels mangler. Jeg har derfor kun testet installations og placering af order.

- Stylingen af Smart Send indstillingerne er røget. Der mangler noget spacing på de øverste settings, så de kommer til at ligne de nederste.
- Der bliver vist afhentningssteder korrekt på checkout siden
- Meta data bliver fint gemt på ordren.
- Shipping methods bliver korrekt gemt
- Der bliver ikke gemt nogle log filer, når der fx bliver placeret en ordre til et afhentningssted.

![Image](https://github.com/smartsendio/woocommerce/assets/62544616/b8d4440d-2e05-49c2-a1c4-ecf0b5ea631a)
![Image](https://github.com/smartsendio/woocommerce/assets/62544616/f3bd29ea-e37e-4ac1-af6b-367dae47204b)
![Image](https://github.com/smartsendio/woocommerce/assets/62544616/9fa060a5-36e4-4e4b-b67a-a74552641520)

**Comment by bilfeldt** [comment]
Fixed
